### ISSUE TITLE
Is split doing it right?

### ISSUE THREAD

**Issue by arademaker** [edicl/cl-ppcre#21]
Is cl-ppcre:split doing it right?  

```
harem> (cl-ppcre:split "\\|" "|OUTRO")
("" "OUTRO")
harem> (cl-ppcre:split "\\|" "OUTRO|")
("OUTRO")
```

In the second case, I would expect ```("OUTRO" "")```. Ideas?

**Comment by hanshuebner** [comment]
Please refer to the documentation: http://weitz.de/cl-ppcre/#split

2015-01-29 11:29 GMT-05:00 Alexandre Rademaker <notifications@github.com>:

**Comment by arademaker** [comment]
you are right, using :limit I managed to control it. Sorry.
