### ISSUE TITLE
Removing (safety 0)

### ISSUE THREAD

**Issue by stassats** [edicl/cl-ppcre#26]
Using (safety 0) everywhere by default is quite a poor choice, it leads to hard to debug situations when things are used wrong, like bad indexes or if the result of create-scanner is called with a wrong number of arguments. Worse, it could lead to silent data corruption. I don't think the slight speed up is worth the headache.

**Comment by stassats** [comment]
Perhaps some other implementations benefit from it more than SBCL, so the first step would be to measure the difference. And if it's actually required somewhere, apply it only where it matters.

**Comment by stassats** [comment]
And other stuff has (safety 0), so if it's changed it needs to be changed everywhere, not just in cl-ppcre.

**Comment by attila-lendvai** [comment]
i've been bit by exactly this just recently.

**Comment by stassats** [comment]
Any opinion on this?

**Comment by hanshuebner** [comment]
I think `(safety 0)` should never be enabled by a library by default.  Rather, this should be a choice made by a user.  I will not be able to put any time into measuring differences, but why not remove it and update the documentation that, depending on the implementation, an application that uses `cl-ppcre` a lot might see performance improvements with `(safety 0)` enabled, depending on the implementation?

**Comment by attila-lendvai** [comment]
FTR, i've created a PR for this: https://github.com/edicl/cl-ppcre/pull/29
