### ISSUE TITLE
single-character RE broken?

### ISSUE THREAD

**Issue by phmarek** [edicl/cl-ppcre#28]
Hi, there's something I don't understand. The following snippet uses a single-character RE - and gets a match (wrongly), at invalid positions. When using a two-character RE, it correctly gives `NIL`.

```lisp
(let ((regex842 "k")
      (string "1 a 312"))
  (multiple-value-bind (cregex843 mregex844)
    (let ((cl-ppcre:*allow-named-registers* t))
      (cl-ppcre:create-scanner regex842))
    (print (list cregex843 mregex844))
    (multiple-value-bind (begin846 end847 starts848 ends849)
      (funcall cregex843 string 0 nil)
      ;(cl-ppcre:scan regex842 string :start 0 :end nil)
      (print (list begin846 end847 starts848 ends849))
      (print (list string regex842)))))
```

Either version (with the precompiled scanner function, and the direct call to SCAN) fail.

Example results (actual values different each time):

```
(415 416 #() #()) 
("1 a 312" "q") 
("1 a 312" "q")

(16589 16590 #() #()) 
("1 a 312" "k") 
("1 a 312" "k")
```

This is with git HEAD (26aa9b68fb59cc18d216efe0f15d535eb11a2d5a),   and SBCL 1.3.3.debian.

Help, please?

**Comment by phmarek** [comment]
`[q]` as RE does work, though.

**Comment by phmarek** [comment]
The problem is the `:END NIL`:
```lisp
(print (list
         (cl-ppcre:scan "h" "999")
         (cl-ppcre:scan "h" "999" :start 0)
         (cl-ppcre:scan "h" "999" :start 0 :end nil)))
(NIL NIL 72)
```

**Comment by phmarek** [comment]
Nearly funny.

```lisp
(print (list
         (cl-ppcre:scan "h" "999" :end 27)
         (cl-ppcre:scan "h" "999" :end 28)
         (cl-ppcre:scan "h" "999" :end 29)
         (cl-ppcre:scan "h" "999" :end 30)
         (cl-ppcre:scan "h" "999" :end nil)
         ))
(NIL NIL 28 28 72) 
```

**Comment by phmarek** [comment]
clisp reports `SCHAR: index 3 should be less than the length of the string`, ECL says `3 is not a valid index into the object "999"`, so it seems to be an SBCL bug.

**Comment by stassats** [comment]
This is due to #26
