### ISSUE TITLE
http://weitz.de/cl-ppcre/ is 404

### ISSUE THREAD

**Issue by myrkraverk** [edicl/cl-ppcre#33]
The documentation at http://weitz.de/cl-ppcre/ is gone.  Please fix or upload somewhere.

**Comment by michipili** [comment]
@myrkraverk  It looks like the documentation is also available here. https://common-lisp.net/~loliveira/ediware/cl-ppcre/doc/

**Comment by stassats** [comment]
If anyone is willing to contribute, the documentation can be made available through github pages. And weitz.de could redirect there. But I don't have time to do that myself.

**Comment by stassats** [comment]
And not just for cl-ppcre, for all edicl projects.

**Comment by myrkraverk** [comment]
I have been using

    ~/quicklisp/dists/quicklisp/software/cl-ppcre-2.0.11/doc/index.html

as a workaround.

**Comment by vityok** [comment]
@stassats is it still possible to include a workaround, like the one provided by @myrkraverk above, to the project's README file, where it is most likely to be seen by those who look for them?

**Comment by vityok** [comment]
P.S. just noticed that there is a very "unofficial" documentation page on Quicklisp.org:
https://www.quicklisp.org/beta/UNOFFICIAL/docs/cl-ppcre/doc/index.html

the same applies to other packaged developed by Mr. Weitz (flexi-streams, etc)

**Comment by stassats** [comment]
The "doc/" directory is already named conspicuously enough. The real solution is hosting all the files through github pages.

**Comment by vityok** [comment]
@stassats hi Stas, according to the docs project owners are the ones who can enable Github pages and configure them to use project's docs/ directory as the publishing source or create Github pages for the whole "username".

According to the Jekyll documentation, it might be even possible to feed it HTML files as the source (instead of Markdown).

IMHO, resolving the issue with hidden documentation is quite important, especially for new Lisp developers who can be disappointed with this situation.

Would you please be so kind as to initialize repository for Github pages for the `edicl` "user". This should make it possible for others to contribute to it.

Thanks!

**Comment by stassats** [comment]
I made
https://edicl.github.io/cl-ppcre/
and
https://edicl.github.io/

I'll give the necessary commit bits to anyone who will do that for all other repositories, adjust all the links within the docs, and make a page at http://edicl.github.io which links them all.

**Comment by vityok** [comment]
Hi @stassats 

great start. Thanks!

I've been able to find the edicl.github.io repository, which happens to have that "empty" index.html file. But I still don't understand where/how the cl-ppcre directory is created. Is it tuned to use cl-ppcre/doc as its source? If so, could you please do the same to the rest of the projects, and I'll update the edicl.github.io repository to link them all?

With best regards

**Comment by stassats** [comment]
I can you give the rights to publish the docs/ directories from all other repos. (The directory has to be renamed from doc/ to docs/, though).

**Comment by stassats** [comment]
![image](https://user-images.githubusercontent.com/10473/34220022-16147ae0-e5c4-11e7-8aa7-8b44480481cc.png)

**Comment by vityok** [comment]
Hi @stassats ,

well, if it is possible, yes, I would like to have the documentation for all other projects republished at the known location.

Let's see if it is possible to grant such permissions and it will work at all.

With best regards

**Comment by stassats** [comment]
I sent you an "invite" yesterday, have you received it?

**Comment by vityok** [comment]
Hi @stassats,

didn't check e-mail. Now fixed. And it works: http://edicl.github.io/cl-who/

Will proceed to do the same for other projects and add links to the docs in their README files (and create them if missing).

Thanks!

IMHO this ticket can be resolved as fixed and closed now.

**Comment by stassats** [comment]
Thank you. Will close after everything is done. Will also submit a list of new pages to Edi to set up redirects from weitz.de

**Comment by stassats** [comment]
The references to weitz.de in the html files would need to be updated as well.

**Comment by vityok** [comment]
Hi @stassats,

at least PPCRE is more or less brought to life already. IMHO the way documentation is created should be changed towards automatic generation via declt or similar.

meanwhile, see commit f173c78cabd61d861cc9d1ae68f9d6ca0415ab18

With best regards

**Comment by stassats** [comment]
Not the whole documentation is generated from docstrings, though some parts like functions signatures could be automated.

And the download link should probably go to https://github.com/edicl/cl-ppcre/releases not the current master.

**Comment by stassats** [comment]
Ok, I submitted a list of redirects to Edi. Everything should go back to normal.

**Comment by stassats** [comment]
And thanks for the help. People who read documentation (a dying breed) will appreciate it.
