### ISSUE TITLE
Inconsistency with split

### ISSUE THREAD

**Issue by cage2** [edicl/cl-ppcre#44]
Hi!

I found the values returned by split bit strange sometimes, in particular:

``` lisp
(cl-ppcre:split "a" "aa") ; => nil
```
but

``` lisp
(cl-ppcre:split "a" "aab") ; =>  ("" "" "b")
```

Is not that strange?

Bye!
C.

**Comment by stassats** [comment]
No. 

> If limit is NIL (or 0 which is equivalent), trailing empty strings are removed from the result list.

If you want that behavior set limit to -1.

**Comment by cage2** [comment]
On Fri, Apr 09, 2021 at 10:54:34AM -0700, Stas Boukarev wrote:

Hi!

> No.
>
> > If limit is NIL (or 0 which is equivalent), trailing empty strings are removed from the result list.
>
> If you want that behavior set limit to -1.

Sorry i was not able to read the doc properly!

Thank you for your quick reply! :)
Bye!
C.

**Comment by stassats** [comment]
I guess the part about -1 should be documented as well.
