### ISSUE TITLE
crash building in SBCL with certain high safety low speed compiler policy

### ISSUE THREAD

**Issue by markhdavid** [edicl/cl-ppcre#45]
When I build with a certain high-safety, low-speed compiler policy, it goes into the debugger in `SB-C::VOP-OPTIMIZE-BOUNDP-OPTIMIZER`.  Using SBCL 2.1.9 and the cl-ppcre-20190521 distribution of CL-PPCRE, which is the current Quicklisp distribution.  I set compiler policy with the following series of commands: (log:)
```
* (sb-ext:restrict-compiler-policy 'speed 0 0)
NIL
((SPEED . 0))
* (sb-ext:restrict-compiler-policy 'safety 3 3)
((SAFETY . 3))
((SPEED . 0))
* (sb-ext:restrict-compiler-policy 'space 0 0)
((SAFETY . 3))
((SPEED . 0) (SPACE . 0))
* (sb-ext:restrict-compiler-policy 'debug 3 3)
((SAFETY . 3) (DEBUG . 3))
((SPEED . 0) (SPACE . 0))
```

See attached log showing build going into debugger.
[sbcl-crash-with-low-speed-high-safety-loading-cl-ppcre-log.txt](https://github.com/edicl/cl-ppcre/files/7652772/sbcl-crash-with-low-speed-high-safety-loading-cl-ppcre-log.txt)

**Comment by stassats** [comment]
That's not really a cl-ppcre issue, but an SBCL one, isn't it?

**Comment by stassats** [comment]
And I don't see this with SBCL 2.1.11

**Comment by markhdavid** [comment]
Confirmed, not seen in SBCL 2.1.11 [specifically SBCL 2.1.11.41-10ea30f55 on MacOS, built from sources]. Seems it is fixed, so thank you to the SBCL developers.
