### ISSUE TITLE
Several Instances of Unexpected Behavior

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [edicl/cl-ppcre#52]
Hello,

I am using this library to implement my own strings library, and I have run into several instances of unexpected behavior. The first thing that I noticed relates to `ppcre:scan`. I have a function that scans a given string to ensure that every character within said string is alphabetic, but it thinks that numbers are alphabetic. The function in question is as follows.
```
(defun alpha-p (target-string)
  "Determines if TARGET-STRING contains at last one character and all characters are alphabetic."
  (when (ppcre:scan "[a-zA-Z]+$" target-string)
    t))
```
I have written a few tests for this function, which can be seen [here](https://gitlab.com/FOSSilized_Daemon/cl-sml/-/blob/main/src/tests/check-test.lisp#L105), but the one I want to focus on is as follows. If I run the below statement.
```
(alpha-p "1My other string")
```
It should return `nil`, because `1` not alphabetic, However, it always returns true. I, playing around, changed my function to the following.
```
(defun alpha-p (target-string)
  "Determines if TARGET-STRING contains at last one character and all characters are alphabetic."
  (when (ppcre:scan "^[a-zA-Z]+$" target-string)
    t))
```
This caused the aformentioned test to run properly, returning `nil`. However, it then started to fail another test.
```
(alpha-p "My fun string")
```
Now returns `nil` every single time when it should return `T`. I tried changing the entire statement to lowecase letters to no avail and I have gone over this to the point where I cannot find any errors and bugs in my code. When I statements outside of my function directly in a REPL I get the same problems. Is there perhaps a bug in this library? I have also experienced an issue where the following
```
(ppcre:scan "\\p{L}" STRING)
```
Will always return `nil` as well. I do not know enough Common Lisp to properly debug this massive library, have you by chance heard others having this issue?

**Comment by phoe** [comment]
`"My fun string"` contains spaces, which are not `[a-zA-Z]`.

**Comment by FOSSilizedDaemon** [comment]
> `"My fun string"` contains spaces, which are not `[a-zA-Z]`.

It cannot handle whitespace? I could just manually loop through the string then. What about it thinking that numbers are alphabetic? I am confused by the whitespace issue as I have other tests for functions such as [alphanumeric-p](https://gitlab.com/FOSSilized_Daemon/cl-sml/-/blob/main/src/check.lisp#L26) that contain whitespace and have no issue.

**Comment by phoe** [comment]
If you tell your regular expression to not match on space characters, then it will not match on space characters.

```lisp
CL-USER> (if (ppcre:scan "^[a-zA-Z]+$" "foo bar baz") t nil)
NIL

CL-USER> (if (ppcre:scan "^[a-zA-Z ]+$" "foo bar baz") t nil)
T
```

**Comment by FOSSilizedDaemon** [comment]
> If you tell your regular expression to not match on space characters, then it will not match on space characters.
> 
> ```lisp
> CL-USER> (if (ppcre:scan "^[a-zA-Z]+$" "foo bar baz") t nil)
> NIL
> 
> CL-USER> (if (ppcre:scan "^[a-zA-Z ]+$" "foo bar baz") t nil)
> T
> ```

I was able to get that fixed, but for the future is there any work around for ppcre matching numbers as alphabetic and {L} always returning nil when used?

**Comment by FOSSilizedDaemon** [comment]
@phoe Can you provide me with the updated documentation? For some reason I am not getting consistent behavior, when I run this test with anything that is not alpha, such as punctuation, or numbers I keep getting a T return when it should be nil and I cannot figure out why.

**Comment by phoe** [comment]
> when I run this test

Which one in particular? Can you post code snippets that document this behavior, preferably as minimal as possible?

**Comment by FOSSilizedDaemon** [comment]
> > when I run this test
> 
> Which one in particular? Can you post code snippets that document this behavior, preferably as minimal as possible?

It was an error due to sbcl pulling from cache instead of my updated codebase (which it would not do that, but I digress). That issue seems to be me messing up my regex, my bad. That said, do you have any information on \\p{L} always returning nil? Perhaps I am using it wrong, I do not know perl regex, but when I try
```
(ppcre:scan "\\p{L}" "a")
```
I get nil. Shouldn't it be true?

**Comment by phoe** [comment]
Looks like `L` or `Letter` is a Unicode-defined property. After `(ql:quickload :cl-ppcre-unicode)`, the value of [`ppcre:*property-resolver*`](http://edicl.github.io/cl-ppcre/#*property-resolver*) becomes [`CL-PPCRE-UNICODE:UNICODE-PROPERTY-RESOLVER`](http://edicl.github.io/cl-ppcre/#unicode-property-resolver) - it was null before, which is why, IIUC, the property failed to resolve.

After quickloading the above, `(ppcre:scan "\\p{L}" "a")` starts returning true.

**Comment by FOSSilizedDaemon** [comment]
> Looks like `L` or `Letter` is a Unicode-defined property. After `(ql:quickload :cl-ppcre-unicode)`, the value of [`ppcre:*property-resolver*`](http://edicl.github.io/cl-ppcre/#*property-resolver*) becomes [`CL-PPCRE-UNICODE:UNICODE-PROPERTY-RESOLVER`](http://edicl.github.io/cl-ppcre/#unicode-property-resolver) - it was null before, which is why, IIUC, the property failed to resolve.
> 
> After quickloading the above, `(ppcre:scan "\\p{L}" "a")` starts returning true.

Ohhhh, that makes sense. All good now!
