### ISSUE TITLE
Does :RANGE work improperly (at least in SBCL 2.3.8 on Linux)?

### ISSUE THREAD

**Issue by Lispl-Wicht** [edicl/cl-ppcre#55]
While I'm familiarising myself with the library and Regexp with the Perl tutorial (https://perldoc.perl.org/perlretut) I stumbled upon this:

`(ppcre:parse-string "[0-9a-fA-F]")`
`;; => (:CHAR-CLASS (:RANGE #\0 #\9) (:RANGE #\a #\f)  (:RANGE #\A #\F))`
`(ppcre:scan "[0-9a-fA-F]" "0BaC16")`
`;; => 0, 1, #(), #()`
`(ppcre:scan "[0-9a-fA-F]" "G7Staaten") `
`;; => 1, 2, #(), #() -> BUG?`
`(ppcre:scan (ppcre:parse-string "[0-9a-fA-F]" "G7Staaten")`
`;; => 1, 2, #(), #() -> BUG?`

It's from this in the mentioned tutorial:

`/item[0-9]/;  # matches 'item0' or ... or 'item9'`
`/[0-9bx-z]aa/;  # matches '0aa', ..., '9aa',`
`                          # 'baa', 'xaa', 'yaa', or 'zaa'`
`/[0-9a-fA-F]/;  # matches a hexadecimal digit`
`/[0-9a-zA-Z_]/; # matches a "word" character,
`                # like those in a Perl variable name`

By the way, I couldn't reproduce this example as well:
`$x = 'bcr';`
`/[$x]at/;   # matches 'bat', 'cat', or 'rat'`
`/[\$x]at/;  # matches '$at' or 'xat'`
`/[\\$x]at/; # matches '\at', 'bat, 'cat', or 'rat'`

I got this:

`;; Different from the Perl related tutorium, in CL-PPCRE the $`
`;; seems not denote a scalar variable in a character class`
`;; - of CL-PPCRE. So here $ is not a special character:`
`(defparameter x "bcr")`
(ppcre:parse-string "[$x]at")   ; => (:SEQUENCE (:CHAR-CLASS #\$ #\x) "at")
(ppcre:parse-string "[\$x]at")  ; => (:SEQUENCE (:CHAR-CLASS #\$ #\x) "at")
(ppcre:parse-string "[\\$x]at") ; => (:SEQUENCE (:CHAR-CLASS #\$ #\x) "at")
(ppcre:scan "[$x]at" "bat")     ; => NIL -> same with \$ and \\$, of course`

But I thought this isn't an issue but a decision.

**Comment by phoe** [comment]
Why would `(ppcre:scan "[0-9a-fA-F]" "G7Staaten")` be a bug? `[0-9a-fA-F]` states that you are looking for a single character that's a effectively hex digit (disregarding case). The 0th char, `G` is not a match, and the 1st one, `7`, is - hence you get a match at position `1` that is one char long, giving you the end marker at `2`.

**Comment by Lispl-Wicht** [comment]
Wow, that's fast.
Apparently I misunderstood it. 
I thought it would be NIL.
Maybe I was irritated by this:
`(ppcre:scan "[0-9bx-z]aa" "7aa")   ; => 0, 3, #(), #()`
But then: Three characters were found that matched. Yes.
Can I delete this request?

**Comment by phoe** [comment]
Sure, all is OK. (As they say, if you have a problem and you use regex to solve it, now you have two problems.)

**Comment by Lispl-Wicht** [comment]
Thats encouraging :-) 
Well, at the moment I stay naively curious :-)

**Comment by Lispl-Wicht** [comment]
... I ... would delete it. But I do not find the delete button. So, I hope it is enough to close it.
