### ISSUE TITLE
Illegal substring "\\0" in replacement string.

### ISSUE THREAD

**Issue by jf7t2gd1n** [edicl/cl-ppcre#56]
Thanks for this great ppcre system.

I have encountered an issue in some cases of the replacement string. If, for example, the replacement string has \0 , an error appears:
  Illegal substring "\\0" in replacement string.

In Perl this issue does not seem to appear.

Is it possible to work around it?

Best regards.

```
;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;
;; A simple example  (in SBCL):
(ppcre:regex-replace "cd" "Abcd" "\\0")

debugger invoked on a CL-PPCRE:PPCRE-INVOCATION-ERROR in thread
#<THREAD "main thread" RUNNING {1004E281B3}>:
  Illegal substring "\\0" in replacement string.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

((:METHOD CL-PPCRE::BUILD-REPLACEMENT-TEMPLATE (STRING)) #<unavailable argument>) [fast-method]
   source: (WHEN (< FROM (LENGTH REPLACEMENT-STRING))
             (PUSH (SUBSEQ REPLACEMENT-STRING FROM) COLLECTOR))
0] 
;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;
```

**Comment by phoe** [comment]
Are you looking for `(ppcre:regex-replace "cd" "Abcd" (string (code-char 0)))`? Lisp does not escape \0 in strings if you want to have a string containing the null character.

Alternatively, load `cl-interpol`, call `(cl-interpol:enable-interpol-syntax)`, and do `(ppcre:regex-replace "cd" "Abcd" #?"\0")`.

**Comment by nibbula** [comment]
You might be thinking of \0 as a backreference to the whole match as in sed:
`sed -e 's/foo/==\0==/g'`
but this doesn't work in perl where it means the ASCII NUL (code 0) character:
`perl -p -e 's/foo/==\0==/g'`

A workaround is to use \1 and a group, e.g.:
`(ppcre:regex-replace "(cd)" "Abcdef" "==\\1==")`

**Comment by jf7t2gd1n** [comment]
Thanks for your answers.

Let me add another simple example :

I have encountered this issue sometimes when I want to replace some lines of C code, for example from:
if (c1 == '5')
to
if (c1 == '\0')

I would like to use ppcre:regex-replace on the if condition expression (delimitated by parenthesis) and I would like the target string to be
if (c1 == '5')

Is that possible?

https://edicl.github.io/cl-ppcre/#regex-replace

Thank you very much.

**Comment by jf7t2gd1n** [comment]
Thanks a lot. I think that is it.
(format t "~A~%" (ppcre:regex-replace "'5'" "if (c1 == '5')" "'\\\\0'"))
if (c1 == '\0')
